### ISSUE TITLE
Translate the question 421-435

### ISSUE THREAD

**Issue by amirmalekian** [Mariotek/javascript-persian-interview-questions#17]
Hi @sayjeyhi,
I wanted to get an inquiry from the translation status that if someone did not start translating the rest of the repo, I would do it.

**Comment by sayjeyhi** [comment]
Hey @amirmalekian jan,
TBH the translation is almost done, but we are in the process of fixing translation issues, so if you involved fixing it, that could be great!

I've updated this issue:
https://github.com/Mariotek/javascript-persian-interview-questions/issues/3

and if you want to pick a piece of work, just let me know.


## Fix translation issues

- [ ] 0 - 50
- [ ] 50 - 100
- [ ] 100 - 150
- [ ] 150 - 200
- [ ] 200 - 250
- [ ] 250 - 300
- [ ] 300 - 350
- [ ] 350 - 400
- [ ] 400 - 420

**Comment by amirmalekian** [comment]
that's great,
ok thanks
