### ISSUE TITLE
Translate status

### ISSUE THREAD

**Issue by sayjeyhi** [Mariotek/javascript-persian-interview-questions#3]
## Codes RTL

- [x] 100% completed

## Translate questions

- [x] 0 - 20
- [x] 20 - 40
- [x] 40 - 60
- [x] 60 - 80
- [x] 80 - 100
- [x] 100 - 120
- [x] 120 - 140
- [x] 140 - 160
- [x] 160 - 180
- [x] 180 - 200
- [x] 200 - 220
- [x]  240 - 240
- [x]  240 - 260
- [x]  260 - 280
- [x]  280 - 300
- [x]  300 - 320
- [x]  320 - 340
- [x]  340 - 360
- [x]  360 - 380
- [x]  380 - 400
- [x]  400 - 420

## Persian URL fixes

- [x] 0% completed

## Answers Translate status

- [x] 0 - 20
- [x] 20 - 40
- [x] 40 - 60
- [x] 60 - 80
- [x] 80 - 100
- [x] 100 - 120
- [x] 120 - 140
- [x] 140 - 160
- [x] 160 - 180
- [x] 180 - 200
- [x] 200 - 220
- [x]  240 - 240
- [x]  240 - 260
- [x]  260 - 280
- [x]  280 - 300
- [x]  300 - 320
- [x]  320 - 340
- [x]  340 - 360
- [x]  360 - 380
- [x]  380 - 400
- [x]  400 - 420

## Code practice

- [x]  0 - 10
- [x]  10 - 20
- [x]  20 - 30
- [x]  30 - 40
- [x]  40 - 50
- [x]  50 - 55

## Fix translation issues

- [ ] 0 - 50
- [ ] 50 - 100
- [ ] 100 - 150
- [ ] 150 - 200
- [ ] 200 - 250
- [ ] 250 - 300
- [ ] 300 - 350
- [ ] 350 - 400
- [ ] 400 - 420

**Comment by mesbah68** [comment]
> ## Codes RTL
> * [x]  100% completed
> 
> ## Translate questions
> * [ ]  0 - 20
> * [ ]  20 - 40
> * [ ]  40 - 60
> * [ ]  60 - 80
> * [ ]  80 - 100
> * [ ]  100 - 120
> * [ ]  120 - 140
> * [ ]  140 - 160
> * [ ]  160 - 180
> * [ ]  180 - 200
> * [ ]  200 - 220
> * [ ]   240 - 240
> * [ ]   240 - 260
> * [ ]   260 - 280
> * [ ]   280 - 300
> * [ ]   300 - 320
> * [ ]   320 - 340
> * [ ]   340 - 360
> * [ ]   360 - 380
> * [ ]   380 - 400
> * [ ]   400 - 420
> 
> ## Persian URL fixes
> * [ ]  0% completed
> 
> ## Answers Translate status
> * [x]  0 - 20
> * [x]  20 - 40
> * [x]  40 - 60
> * [ ]  60 - 80
> * [ ]  80 - 100
> * [ ]  100 - 120
> * [ ]  120 - 140
> * [ ]  140 - 160
> * [ ]  160 - 180
> * [ ]  180 - 200
> * [ ]  200 - 220
> * [ ]   240 - 240
> * [ ]   240 - 260
> * [ ]   260 - 280
> * [ ]   280 - 300
> * [ ]   300 - 320
> * [ ]   320 - 340
> * [ ]   340 - 360
> * [ ]   360 - 380
> * [ ]   380 - 400
> * [ ]   400 - 420
> 
> ## Code practice
> * [ ]   0 - 10
> * [ ]   10 - 20
> * [ ]   20 - 30
> * [ ]   30 - 40
> * [ ]   40 - 50
> * [ ]   50 - 55
