### ISSUE TITLE
Improvement Q-408

### ISSUE THREAD

**Issue by hasanisaeed** [Mariotek/javascript-persian-interview-questions#31]
سوال ۴۰۸: 
> هم برای...in و هم برای...از دستورات روی ساختارهای داده js تکرار می‌شن.

قشنگ ترجمه نشده. پیشنهاد من اینه که جمله زیر رو جایگزین کنین.

از for...in و for...of  برای پیمایش بر روی داده ها با خاصیت تکرار (مانند آرایه ها)، استفاده می‌شه.

**Comment by sayjeyhi** [comment]
@eisa-rezaei

**Comment by realsaeedhassani** [comment]
@eisa-rezaei I close this issue as `completed`
