### ISSUE TITLE
شروع ترجمه  سوالات مصاحبه انگولاری

### ISSUE THREAD

**Issue by ehsanlotfi** [Mariotek/javascript-persian-interview-questions#35]
برای شروع لینک زیر را پیشنهاد میکنم 

https://github.com/sudheerj/angular-interview-questions

برای 10 تای اول داوطلبم.

**Comment by sayjeyhi** [comment]
سلام احسان جان، عذر میخوام دیر پاسخ میدم
فکر کنم عیسی تا ۱۰۰ رو رفته بود، اگه میتونی از ۱۵۰-۲۰۰ رو بزن و
بی زحمت اگر قصد مشارکت داری روی ریپو خود انگولار مطرح کن.
مرسی
