### ISSUE TITLE
Cover

### ISSUE THREAD

**Issue by sayjeyhi** [Mariotek/javascript-persian-interview-questions#36]
[JavascriptBook-cover.psd.zip](https://github.com/Mariotek/javascript-persian-interview-questions/files/10307510/JavascriptBook-cover.psd.zip)

**Comment by god-of-javascript** [comment]
![JavascriptBook-cover](https://github.com/Mariotek/javascript-persian-interview-questions/assets/124286495/81ef19c6-81b4-4535-a628-2233334b8f29)
