### ISSUE TITLE
Broken links in markdown

### ISSUE THREAD

**Issue by emadbaqeri** [Mariotek/javascript-persian-interview-questions#5]
I was reading the documentation and I saw some broken links.
e.g. 
[this one here in the markdown preview file](https://github.com/Mariotek/javascript-persian-interview-questions/blob/master)

**Comment by sayjeyhi** [comment]
Hi Emad jan,
Yeah, almost all links are broken because it is not finished yet, TBH and I don't have time to work on it yet.

**Comment by emadbaqeri** [comment]
Hi @sayjeyhi,
I can help you with this

**Comment by sayjeyhi** [comment]
@emadbaqeri It could be great... I updated the book translation and links, so translated links are working fine now, but about other links, I removed the `href`, so what you can do is, if you could translate the remaining question titles in `book.md` file TOC (without links) It could be so useful, and I can easily replace titles in answers and links then we can use it. 

For e.g: From question 126 you can start translating just the title inside `[` and `]` and open PR like:
`|126| [How do you loop through or enumerate javascript object]() |`
to:
`|126| [متن فارسی ترجمه شده]() |`

**Comment by emadbaqeri** [comment]
@sayjeyhi Alright, I'm going to start doing it in the Tuesday Evening. We should stay in touch because I'm the one that always have questions to ask.
